import os
import json
import requests

class DeepSeekMultiAgentGrader:
    """
    A multi-agent system for generating and grading mathematical proofs
    using the DeepSeek Prover V2 API.

    This system consists of two agents:
    1. Formulator Agent: Generates a proof for a given mathematical question.
    2. Refiner/Grader Agent: Refines and grades the proof generated by the Formulator.
    """

    def __init__(self, api_key: str, api_url: str = "https://openrouter.ai/api/v1/chat/completions"):
        """
        Initializes the grading system with the necessary API credentials.

        Args:
            api_key (str): The API key for accessing the DeepSeek Prover V2 model.
            api_url (str): The URL of the API endpoint.
        """
        if not api_key:
            raise ValueError("API key cannot be empty.")
        self.api_key = api_key
        self.api_url = api_url
        self.headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

    def _call_deepseek_api(self, system_prompt: str, user_prompt: str) -> dict:
        """
        A helper function to make a call to the DeepSeek Prover V2 API.

        Args:
            system_prompt (str): The system message to guide the AI's role and output format.
            user_prompt (str): The user's query or the input for the agent.

        Returns:
            dict: The JSON response from the API, parsed as a dictionary.
        """
        body = {
            "model": "deepseek/deepseek-prover-v2",
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
        }
        try:
            response = requests.post(self.api_url, headers=self.headers, data=json.dumps(body))
            response.raise_for_status()  # Raises an HTTPError for bad responses (4xx or 5xx)
            content = response.json()['choices'][0]['message']['content']
            return json.loads(content)
        except requests.exceptions.RequestException as e:
            print(f"An error occurred during the API request: {e}")
            return None
        except json.JSONDecodeError:
            print("Failed to decode the API response as JSON.")
            print(f"Raw response: {response.text}")
            return None

    def formulate_proof(self, question: str) -> dict:
        """
        The Formulator Agent.

        Takes a mathematical question and generates a formal proof in Lean 4,
        structured in a JSON format.

        Args:
            question (str): The mathematical statement to be proven.

        Returns:
            dict: A dictionary containing the proof, explanation, and subgoals.
        """
        print("🤖 Formulator Agent: Generating the initial proof...")
        system_prompt = """
        You are an expert mathematician and a specialist in the Lean 4 proof assistant.
        Your task is to generate a formal proof for a given mathematical statement.
        You must provide your response as a JSON object with the following structure:
        {
          "question": "The original question",
          "lean_proof": "The complete Lean 4 code for the proof.",
          "explanation": "A clear, natural language explanation of the proof strategy.",
          "subgoals": ["A list of the main subgoals or steps in the proof."]
        }
        Ensure the JSON is well-formed.
        """
        user_prompt = f"Generate a formal proof for the following statement: {question}"

        return self._call_deepseek_api(system_prompt, user_prompt)

    def refine_and_grade_proof(self, proof_data: dict) -> dict:
        """
        The Refiner/Grader Agent.

        Takes the output from the Formulator, grades it based on multiple criteria,
        and provides a refined version of the proof.

        Args:
            proof_data (dict): The JSON output from the formulate_proof method.

        Returns:
            dict: A dictionary containing the grading report and the refined proof.
        """
        print("🧐 Refiner/Grader Agent: Analyzing and grading the proof...")
        system_prompt = """
        You are a university professor specializing in formal methods and mathematical logic.
        Your task is to review and grade a formal proof written in Lean 4.
        You will be given a JSON object containing the proof.
        Analyze the proof based on the following criteria:
        1.  Correctness & Completeness: Is the proof logically sound and complete?
        2.  Clarity & Readability: Is the Lean 4 code and the explanation clear and easy to understand?
        3.  Efficiency of Tactics: Does the proof use efficient and standard Lean 4 tactics?
        4.  Proof Structure: Is the proof well-structured with a logical flow and good use of subgoals?

        Provide a grade from 1 to 10 for each criterion, along with detailed feedback.
        Finally, provide a refined version of the Lean 4 proof.

        Your response MUST be a JSON object with the following structure:
        {
          "original_proof": { ... the original proof data ... },
          "grading_report": {
            "correctness": {"score": <int>, "feedback": "<text>"},
            "clarity": {"score": <int>, "feedback": "<text>"},
            "efficiency": {"score": <int>, "feedback": "<text>"},
            "structure": {"score": <int>, "feedback": "<text>"}
          },
          "overall_feedback": "<A summary of the proof's strengths and weaknesses.>",
          "refined_proof": "<The improved Lean 4 code.>"
        }
        Ensure the JSON is well-formed.
        """
        user_prompt = f"Please grade the following proof: {json.dumps(proof_data, indent=2)}"

        return self._call_deepseek_api(system_prompt, user_prompt)


if __name__ == '__main__':
    # It is recommended to set the API key as an environment variable for security.
    # For example: export OPENROUTER_API_KEY='your_api_key'
    api_key = os.getenv("OPENROUTER_API_KEY")

    if not api_key:
        print("Please set the OPENROUTER_API_KEY environment variable.")
    else:
        # 1. Initialize the multi-agent system
        grader_system = DeepSeekMultiAgentGrader(api_key=api_key)

        # 2. Define the proof question
        proof_question = "Prove that for any two sets A and B, their intersection is a subset of A (A ∩ B ⊆ A)."

        # 3. The Formulator Agent generates the initial proof
        initial_proof = grader_system.formulate_proof(proof_question)

        if initial_proof:
            print("\n" + "="*50)
            print("📄 Formulator Agent Output:")
            print(json.dumps(initial_proof, indent=2))
            print("="*50 + "\n")

            # 4. The Refiner/Grader Agent analyzes the proof
            graded_proof = grader_system.refine_and_grade_proof(initial_proof)

            if graded_proof:
                print("\n" + "="*50)
                print("✅ Refiner/Grader Agent Output:")
                print(json.dumps(graded_proof, indent=2))
                print("="*50 + "\n")
