"""add_clip_data_to_proctoring_event

Revision ID: 96997737211a
Revises: d4e8b261b3f6
Create Date: 2026-04-23 21:38:21.932346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96997737211a'
down_revision: Union[str, Sequence[str], None] = 'd4e8b261b3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proctoring_events', sa.Column('clip_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proctoring_events', 'clip_data')
    # ### end Alembic commands ###
