"""Add Grading models

Revision ID: 9c943803c081
Revises: a1b2c3d4e5f6
Create Date: 2026-04-22 00:11:09.719505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c943803c081'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('question_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_runs_attempt_id'), 'grading_runs', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_grading_runs_exam_id'), 'grading_runs', ['exam_id'], unique=False)
    op.create_index(op.f('ix_grading_runs_student_id'), 'grading_runs', ['student_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubrics_question_id'), 'rubrics', ['question_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rubrics_question_id'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_grading_runs_student_id'), table_name='grading_runs')
    op.drop_index(op.f('ix_grading_runs_exam_id'), table_name='grading_runs')
    op.drop_index(op.f('ix_grading_runs_attempt_id'), table_name='grading_runs')
    op.drop_table('grading_runs')
    # ### end Alembic commands ###
